
export const autoPlayerData:{
        rowNum:number,
        gameId:number,
        blueTeamTop:string,
        blueTeamJug:string,
        blueTeamMid:string,
        blueTeamAdc:string,
        blueTeamSup:string,
        redTeamTop:string,
        redTeamJug:string,
        redTeamMid:string,
        redTeamAdc:string,
        redTeamSup:string
    }[] = [
        {rowNum:1, gameId:7389173588, blueTeamTop:'인석', blueTeamJug:'승준', blueTeamMid:'경우', blueTeamAdc:'재섭', blueTeamSup:'대훈', redTeamTop:'문석', redTeamJug:'성재', redTeamMid:'광호', redTeamAdc:'지훈', redTeamSup:'현석'},
        {rowNum:2, gameId:7389279181, blueTeamTop:'성재', blueTeamJug:'지훈', blueTeamMid:'문석', blueTeamAdc:'광호', blueTeamSup:'현석', redTeamTop:'대훈', redTeamJug:'재섭', redTeamMid:'인석', redTeamAdc:'경우', redTeamSup:'승준'},
        {rowNum:3, gameId:7389336543, blueTeamTop:'광호', blueTeamJug:'대훈', blueTeamMid:'인석', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'문석', redTeamJug:'재섭', redTeamMid:'경우', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:4, gameId:7389485402, blueTeamTop:'재섭', blueTeamJug:'승준', blueTeamMid:'경우', blueTeamAdc:'문석', blueTeamSup:'현석', redTeamTop:'인석', redTeamJug:'대훈', redTeamMid:'광호', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:5, gameId:7442713195, blueTeamTop:'문석', blueTeamJug:'인석', blueTeamMid:'성재', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'굴비', redTeamJug:'재섭', redTeamMid:'해용', redTeamAdc:'지훈', redTeamSup:'대훈'},
        {rowNum:6, gameId:7442792366, blueTeamTop:'지훈', blueTeamJug:'해용', blueTeamMid:'굴비', blueTeamAdc:'재섭', blueTeamSup:'대훈', redTeamTop:'인석', redTeamJug:'성재', redTeamMid:'문석', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:7, gameId:7442889331, blueTeamTop:'해용', blueTeamJug:'대훈', blueTeamMid:'재섭', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'굴비', redTeamJug:'인석', redTeamMid:'문석', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:8, gameId:7442990856, blueTeamTop:'문석', blueTeamJug:'굴비', blueTeamMid:'인석', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'대훈', redTeamJug:'해용', redTeamMid:'재섭', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:9, gameId:7443104399, blueTeamTop:'대훈', blueTeamJug:'재섭', blueTeamMid:'해용', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'굴비', redTeamJug:'승준', redTeamMid:'인석', redTeamAdc:'문석', redTeamSup:'성재'},
        {rowNum:10, gameId:7443216616, blueTeamTop:'대훈', blueTeamJug:'재섭', blueTeamMid:'문석', blueTeamAdc:'성재', blueTeamSup:'승준', redTeamTop:'인석', redTeamJug:'해용', redTeamMid:'지훈', redTeamAdc:'굴비', redTeamSup:'현석'},
        {rowNum:11, gameId:7450378540, blueTeamTop:'승준', blueTeamJug:'성재', blueTeamMid:'문석', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'해용', redTeamJug:'정호', redTeamMid:'인석', redTeamAdc:'재섭', redTeamSup:'대훈'},
        {rowNum:12, gameId:7450493494, blueTeamTop:'정호', blueTeamJug:'대훈', blueTeamMid:'인석', blueTeamAdc:'재섭', blueTeamSup:'해용', redTeamTop:'승준', redTeamJug:'문석', redTeamMid:'성재', redTeamAdc:'지훈', redTeamSup:'현석'},
        {rowNum:13, gameId:7450598630, blueTeamTop:'성재', blueTeamJug:'지훈', blueTeamMid:'승준', blueTeamAdc:'문석', blueTeamSup:'현석', redTeamTop:'정호', redTeamJug:'재섭', redTeamMid:'해용', redTeamAdc:'인석', redTeamSup:'대훈'},
        {rowNum:14, gameId:7450699576, blueTeamTop:'성재', blueTeamJug:'대훈', blueTeamMid:'인석', blueTeamAdc:'해용', blueTeamSup:'승준', redTeamTop:'정호', redTeamJug:'문석', redTeamMid:'지훈', redTeamAdc:'재섭', redTeamSup:'현석'},
        {rowNum:15, gameId:7450763320, blueTeamTop:'대훈', blueTeamJug:'승준', blueTeamMid:'재섭', blueTeamAdc:'정호', blueTeamSup:'문석', redTeamTop:'인석', redTeamJug:'해용', redTeamMid:'성재', redTeamAdc:'지훈', redTeamSup:'현석'},
        {rowNum:16, gameId:7502087331, blueTeamTop:'인석', blueTeamJug:'성재', blueTeamMid:'광호', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'해용', redTeamJug:'재섭', redTeamMid:'문석', redTeamAdc:'승준', redTeamSup:'대훈'},
        {rowNum:17, gameId:7502173309, blueTeamTop:'대훈', blueTeamJug:'승준', blueTeamMid:'재섭', blueTeamAdc:'해용', blueTeamSup:'문석', redTeamTop:'광호', redTeamJug:'지훈', redTeamMid:'성재', redTeamAdc:'인석', redTeamSup:'현석'},
        {rowNum:18, gameId:7502237027, blueTeamTop:'광호', blueTeamJug:'지훈', blueTeamMid:'인석', blueTeamAdc:'성재', blueTeamSup:'현석', redTeamTop:'대훈', redTeamJug:'문석', redTeamMid:'해용', redTeamAdc:'재섭', redTeamSup:'승준'},
        {rowNum:19, gameId:7502324018, blueTeamTop:'문석', blueTeamJug:'승준', blueTeamMid:'대훈', blueTeamAdc:'재섭', blueTeamSup:'해용', redTeamTop:'인석', redTeamJug:'성재', redTeamMid:'광호', redTeamAdc:'지훈', redTeamSup:'현석'},
        {rowNum:20, gameId:7502433024, blueTeamTop:'인석', blueTeamJug:'성재', blueTeamMid:'광호', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'문석', redTeamJug:'재섭', redTeamMid:'해용', redTeamAdc:'승준', redTeamSup:'대훈'},
        {rowNum:21, gameId:7502556457, blueTeamTop:'문석', blueTeamJug:'재섭', blueTeamMid:'해용', blueTeamAdc:'지훈', blueTeamSup:'대훈', redTeamTop:'인석', redTeamJug:'성재', redTeamMid:'승준', redTeamAdc:'광호', redTeamSup:'현석'},
        {rowNum:22, gameId:7502659665, blueTeamTop:'문석', blueTeamJug:'재섭', blueTeamMid:'광호', blueTeamAdc:'승준', blueTeamSup:'대훈', redTeamTop:'성재', redTeamJug:'인석', redTeamMid:'해용', redTeamAdc:'지훈', redTeamSup:'현석'},
        {rowNum:23, gameId:7502769879, blueTeamTop:'대훈', blueTeamJug:'인석', blueTeamMid:'재섭', blueTeamAdc:'광호', blueTeamSup:'문석', redTeamTop:'성재', redTeamJug:'지훈', redTeamMid:'해용', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:24, gameId:7513016885, blueTeamTop:'인석', blueTeamJug:'지훈', blueTeamMid:'해용', blueTeamAdc:'내색', blueTeamSup:'대방', redTeamTop:'문석', redTeamJug:'재섭', redTeamMid:'광호', redTeamAdc:'승준', redTeamSup:'성재'},
        {rowNum:25, gameId:7513130503, blueTeamTop:'문석', blueTeamJug:'승준', blueTeamMid:'재섭', blueTeamAdc:'광호', blueTeamSup:'성재', redTeamTop:'지훈', redTeamJug:'해용', redTeamMid:'인석', redTeamAdc:'내색', redTeamSup:'대방'},
        {rowNum:26, gameId:7513262561, blueTeamTop:'인석', blueTeamJug:'지훈', blueTeamMid:'해용', blueTeamAdc:'내색', blueTeamSup:'대방', redTeamTop:'재섭', redTeamJug:'광호', redTeamMid:'문석', redTeamAdc:'성재', redTeamSup:'승준'},
        {rowNum:27, gameId:7513354415, blueTeamTop:'성재', blueTeamJug:'승준', blueTeamMid:'광호', blueTeamAdc:'문석', blueTeamSup:'재섭', redTeamTop:'지훈', redTeamJug:'해용', redTeamMid:'인석', redTeamAdc:'내색', redTeamSup:'대방'},
        {rowNum:28, gameId:7513445971, blueTeamTop:'지훈', blueTeamJug:'인석', blueTeamMid:'해용', blueTeamAdc:'내색', blueTeamSup:'대방', redTeamTop:'광호', redTeamJug:'성재', redTeamMid:'승준', redTeamAdc:'재섭', redTeamSup:'문석'},
        {rowNum:29, gameId:7513530035, blueTeamTop:'광호', blueTeamJug:'성재', blueTeamMid:'문석', blueTeamAdc:'재섭', blueTeamSup:'승준', redTeamTop:'해용', redTeamJug:'인석', redTeamMid:'지훈', redTeamAdc:'내색', redTeamSup:'대방'},
        {rowNum:30, gameId:7523345710, blueTeamTop:'성재', blueTeamJug:'재섭', blueTeamMid:'해용', blueTeamAdc:'지훈', blueTeamSup:'문석', redTeamTop:'재희', redTeamJug:'승준', redTeamMid:'광호', redTeamAdc:'경우', redTeamSup:'인석'},
        {rowNum:31, gameId:7523437352, blueTeamTop:'승준', blueTeamJug:'경우', blueTeamMid:'인석', blueTeamAdc:'재희', blueTeamSup:'광호', redTeamTop:'문석', redTeamJug:'성재', redTeamMid:'지훈', redTeamAdc:'재섭', redTeamSup:'해용'},
        {rowNum:32, gameId:7523508506, blueTeamTop:'해용', blueTeamJug:'성재', blueTeamMid:'지훈', blueTeamAdc:'재섭', blueTeamSup:'문석', redTeamTop:'경우', redTeamJug:'재희', redTeamMid:'광호', redTeamAdc:'승준', redTeamSup:'인석'},
        {rowNum:33, gameId:7523613038, blueTeamTop:'재희', blueTeamJug:'인석', blueTeamMid:'광호', blueTeamAdc:'경우', blueTeamSup:'승준', redTeamTop:'성재', redTeamJug:'재섭', redTeamMid:'문석', redTeamAdc:'지훈', redTeamSup:'해용'},
        {rowNum:34, gameId:7523737287, blueTeamTop:'재희', blueTeamJug:'승준', blueTeamMid:'경우', blueTeamAdc:'광호', blueTeamSup:'인석', redTeamTop:'해용', redTeamJug:'재섭', redTeamMid:'문석', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:35, gameId:7523820335, blueTeamTop:'문석', blueTeamJug:'해용', blueTeamMid:'재섭', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'재희', redTeamJug:'인석', redTeamMid:'경우', redTeamAdc:'광호', redTeamSup:'승준'},
        {rowNum:36, gameId:7564075776, blueTeamTop:'광호', blueTeamJug:'재섭', blueTeamMid:'성재', blueTeamAdc:'지훈', blueTeamSup:'인석', redTeamTop:'대훈', redTeamJug:'정호', redTeamMid:'해용', redTeamAdc:'경우', redTeamSup:'승준'},
        {rowNum:37, gameId:7564162106, blueTeamTop:'정호', blueTeamJug:'대훈', blueTeamMid:'승준', blueTeamAdc:'경우', blueTeamSup:'해용', redTeamTop:'재섭', redTeamJug:'인석', redTeamMid:'광호', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:38, gameId:7564227398, blueTeamTop:'재섭', blueTeamJug:'성재', blueTeamMid:'인석', blueTeamAdc:'광호', blueTeamSup:'지훈', redTeamTop:'정호', redTeamJug:'경우', redTeamMid:'해용', redTeamAdc:'대훈', redTeamSup:'승준'},
        {rowNum:39, gameId:7564306026, blueTeamTop:'대훈', blueTeamJug:'경우', blueTeamMid:'정호', blueTeamAdc:'승준', blueTeamSup:'해용', redTeamTop:'인석', redTeamJug:'지훈', redTeamMid:'성재', redTeamAdc:'광호', redTeamSup:'재섭'},
        {rowNum:40, gameId:7564354139, blueTeamTop:'성재', blueTeamJug:'재섭', blueTeamMid:'광호', blueTeamAdc:'지훈', blueTeamSup:'인석', redTeamTop:'해용', redTeamJug:'정호', redTeamMid:'승준', redTeamAdc:'경우', redTeamSup:'대훈'},
        {rowNum:41, gameId:7573287104, blueTeamTop:'문석', blueTeamJug:'성재', blueTeamMid:'지훈', blueTeamAdc:'광호', blueTeamSup:'대훈', redTeamTop:'유민', redTeamJug:'승준', redTeamMid:'재섭', redTeamAdc:'경우', redTeamSup:'인석'},
        {rowNum:42, gameId:7573368098, blueTeamTop:'경우', blueTeamJug:'인석', blueTeamMid:'유민', blueTeamAdc:'승준', blueTeamSup:'문석', redTeamTop:'성재', redTeamJug:'광호', redTeamMid:'재섭', redTeamAdc:'지훈', redTeamSup:'대훈'},
        {rowNum:43, gameId:7573437650, blueTeamTop:'대훈', blueTeamJug:'재섭', blueTeamMid:'광호', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'인석', redTeamJug:'승준', redTeamMid:'경우', redTeamAdc:'문석', redTeamSup:'유민'},
        {rowNum:44, gameId:7573494032, blueTeamTop:'문석', blueTeamJug:'경우', blueTeamMid:'인석', blueTeamAdc:'유민', blueTeamSup:'승준', redTeamTop:'대훈', redTeamJug:'성재', redTeamMid:'재섭', redTeamAdc:'지훈', redTeamSup:'광호'},
        {rowNum:45, gameId:7573526592, blueTeamTop:'성재', blueTeamJug:'지훈', blueTeamMid:'경우', blueTeamAdc:'문석', blueTeamSup:'대훈', redTeamTop:'유민', redTeamJug:'재섭', redTeamMid:'광호', redTeamAdc:'승준', redTeamSup:'인석'},
        {rowNum:46, gameId:7573589418, blueTeamTop:'경우', blueTeamJug:'대훈', blueTeamMid:'광호', blueTeamAdc:'재섭', blueTeamSup:'승준', redTeamTop:'문석', redTeamJug:'인석', redTeamMid:'유민', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:47, gameId:7615805208, blueTeamTop:'해용', blueTeamJug:'승준', blueTeamMid:'정호', blueTeamAdc:'경우', blueTeamSup:'현석', redTeamTop:'태훈', redTeamJug:'인석', redTeamMid:'문석', redTeamAdc:'지훈', redTeamSup:'성재'},
        {rowNum:48, gameId:7615880494, blueTeamTop:'태훈', blueTeamJug:'문석', blueTeamMid:'인석', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'정호', redTeamJug:'승준', redTeamMid:'경우', redTeamAdc:'해용', redTeamSup:'현석'},
        {rowNum:49, gameId:7615971149, blueTeamTop:'해용', blueTeamJug:'정호', blueTeamMid:'경우', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'성재', redTeamJug:'태훈', redTeamMid:'인석', redTeamAdc:'지훈', redTeamSup:'문석'},
        {rowNum:50, gameId:7616037560, blueTeamTop:'태훈', blueTeamJug:'성재', blueTeamMid:'지훈', blueTeamAdc:'문석', blueTeamSup:'인석', redTeamTop:'현석', redTeamJug:'정호', redTeamMid:'승준', redTeamAdc:'경우', redTeamSup:'해용'},
        {rowNum:51, gameId:7616130103, blueTeamTop:'정호', blueTeamJug:'해용', blueTeamMid:'경우', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'인석', redTeamJug:'성재', redTeamMid:'태훈', redTeamAdc:'지훈', redTeamSup:'문석'},
        {rowNum:52, gameId:7616180111, blueTeamTop:'인석', blueTeamJug:'태훈', blueTeamMid:'성재', blueTeamAdc:'지훈', blueTeamSup:'문석', redTeamTop:'정호', redTeamJug:'경우', redTeamMid:'해용', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:53, gameId:7616296480, blueTeamTop:'경우', blueTeamJug:'해용', blueTeamMid:'문석', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'정호', redTeamJug:'성재', redTeamMid:'인석', redTeamAdc:'지훈', redTeamSup:'유민'},
        {rowNum:54, gameId:7616373538, blueTeamTop:'정호', blueTeamJug:'인석', blueTeamMid:'유민', blueTeamAdc:'지훈', blueTeamSup:'성재', redTeamTop:'해용', redTeamJug:'승준', redTeamMid:'문석', redTeamAdc:'경우', redTeamSup:'현석'},
        {rowNum:55, gameId:7627535812, blueTeamTop:'정호', blueTeamJug:'인석', blueTeamMid:'지훈', blueTeamAdc:'경우', blueTeamSup:'대훈', redTeamTop:'문석', redTeamJug:'성재', redTeamMid:'재섭', redTeamAdc:'승준', redTeamSup:'해용'},
        {rowNum:56, gameId:7627620930, blueTeamTop:'성재', blueTeamJug:'해용', blueTeamMid:'재섭', blueTeamAdc:'승준', blueTeamSup:'문석', redTeamTop:'경우', redTeamJug:'대훈', redTeamMid:'정호', redTeamAdc:'지훈', redTeamSup:'인석'},
        {rowNum:57, gameId:7627716729, blueTeamTop:'인석', blueTeamJug:'지훈', blueTeamMid:'경우', blueTeamAdc:'정호', blueTeamSup:'대훈', redTeamTop:'승준', redTeamJug:'재섭', redTeamMid:'문석', redTeamAdc:'해용', redTeamSup:'성재'},
        {rowNum:58, gameId:7627831324, blueTeamTop:'해용', blueTeamJug:'재섭', blueTeamMid:'승준', blueTeamAdc:'문석', blueTeamSup:'성재', redTeamTop:'정호', redTeamJug:'인석', redTeamMid:'지훈', redTeamAdc:'경우', redTeamSup:'대훈'},
        {rowNum:59, gameId:7627909742, blueTeamTop:'지훈', blueTeamJug:'성재', blueTeamMid:'해용', blueTeamAdc:'문석', blueTeamSup:'승준', redTeamTop:'인석', redTeamJug:'재섭', redTeamMid:'경우', redTeamAdc:'정호', redTeamSup:'대훈'},
        {rowNum:60, gameId:7709795533, blueTeamTop:'규창', blueTeamJug:'성재', blueTeamMid:'해용', blueTeamAdc:'승준', blueTeamSup:'대훈', redTeamTop:'지훈', redTeamJug:'재섭', redTeamMid:'문석', redTeamAdc:'광호', redTeamSup:'정호'},
        {rowNum:61, gameId:7709838944, blueTeamTop:'성재', blueTeamJug:'승준', blueTeamMid:'광호', blueTeamAdc:'해용', blueTeamSup:'대훈', redTeamTop:'규창', redTeamJug:'재섭', redTeamMid:'정호', redTeamAdc:'지훈', redTeamSup:'문석'},
        {rowNum:62, gameId:7709935603, blueTeamTop:'규창', blueTeamJug:'재섭', blueTeamMid:'정호', blueTeamAdc:'지훈', blueTeamSup:'문석', redTeamTop:'대훈', redTeamJug:'성재', redTeamMid:'해용', redTeamAdc:'광호', redTeamSup:'승준'},
        {rowNum:63, gameId:7709998273, blueTeamTop:'광호', blueTeamJug:'해용', blueTeamMid:'재섭', blueTeamAdc:'승준', blueTeamSup:'대훈', redTeamTop:'규창', redTeamJug:'성재', redTeamMid:'정호', redTeamAdc:'지훈', redTeamSup:'문석'},
        {rowNum:64, gameId:7710067686, blueTeamTop:'규창', blueTeamJug:'지훈', blueTeamMid:'문석', blueTeamAdc:'정호', blueTeamSup:'성재', redTeamTop:'승준', redTeamJug:'해용', redTeamMid:'재섭', redTeamAdc:'광호', redTeamSup:'대훈'},
        {rowNum:65, gameId:7710150820, blueTeamTop:'규창', blueTeamJug:'성재', blueTeamMid:'지훈', blueTeamAdc:'정호', blueTeamSup:'문석', redTeamTop:'해용', redTeamJug:'대훈', redTeamMid:'재섭', redTeamAdc:'승준', redTeamSup:'광호'},
        {rowNum:66, gameId:7710221890, blueTeamTop:'규창', blueTeamJug:'문석', blueTeamMid:'정호', blueTeamAdc:'재섭', blueTeamSup:'승준', redTeamTop:'성재', redTeamJug:'해용', redTeamMid:'광호', redTeamAdc:'지훈', redTeamSup:'대훈'},
        {rowNum:67, gameId:7768749952, blueTeamTop:'성재', blueTeamJug:'인석', blueTeamMid:'해용', blueTeamAdc:'승준', blueTeamSup:'현석', redTeamTop:'대훈', redTeamJug:'재섭', redTeamMid:'굴비', redTeamAdc:'정호', redTeamSup:'지훈'},
        {rowNum:68, gameId:7768861557, blueTeamTop:'지훈', blueTeamJug:'정호', blueTeamMid:'굴비', blueTeamAdc:'재섭', blueTeamSup:'대훈', redTeamTop:'인석', redTeamJug:'승준', redTeamMid:'해용', redTeamAdc:'성재', redTeamSup:'현석'},
        {rowNum:69, gameId:7768951480, blueTeamTop:'굴비', blueTeamJug:'정호', blueTeamMid:'재섭', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'대훈', redTeamJug:'성재', redTeamMid:'해용', redTeamAdc:'인석', redTeamSup:'승준'},
        {rowNum:70, gameId:7769044477, blueTeamTop:'인석', blueTeamJug:'성재', blueTeamMid:'해용', blueTeamAdc:'지훈', blueTeamSup:'현석', redTeamTop:'재섭', redTeamJug:'대훈', redTeamMid:'굴비', redTeamAdc:'정호', redTeamSup:'승준'},
        {rowNum:71, gameId:7769150584, blueTeamTop:'성재', blueTeamJug:'정호', blueTeamMid:'지훈', blueTeamAdc:'재섭', blueTeamSup:'인석', redTeamTop:'대훈', redTeamJug:'굴비', redTeamMid:'해용', redTeamAdc:'승준', redTeamSup:'현석'},
        {rowNum:72, gameId:7799639480, blueTeamTop:'대훈', blueTeamJug:'정호', blueTeamMid:'해용', blueTeamAdc:'승준', blueTeamSup:'문석', redTeamTop:'성재', redTeamJug:'지훈', redTeamMid:'광호', redTeamAdc:'재섭', redTeamSup:'유민'},
        {rowNum:73, gameId:7799708953, blueTeamTop:'성재', blueTeamJug:'재섭', blueTeamMid:'광호', blueTeamAdc:'지훈', blueTeamSup:'유민', redTeamTop:'정호', redTeamJug:'해용', redTeamMid:'문석', redTeamAdc:'승준', redTeamSup:'대훈'},
        {rowNum:74, gameId:7799787516, blueTeamTop:'정호', blueTeamJug:'승준', blueTeamMid:'문석', blueTeamAdc:'해용', blueTeamSup:'대훈', redTeamTop:'유민', redTeamJug:'광호', redTeamMid:'지훈', redTeamAdc:'재섭', redTeamSup:'성재'},
        {rowNum:75, gameId:7799863622, blueTeamTop:'성재', blueTeamJug:'재섭', blueTeamMid:'지훈', blueTeamAdc:'광호', blueTeamSup:'유민', redTeamTop:'정호', redTeamJug:'대훈', redTeamMid:'해용', redTeamAdc:'문석', redTeamSup:'승준'},
        {rowNum:76, gameId:7799967095, blueTeamTop:'광호', blueTeamJug:'재섭', blueTeamMid:'지훈', blueTeamAdc:'정호', blueTeamSup:'성재', redTeamTop:'문석', redTeamJug:'대훈', redTeamMid:'해용', redTeamAdc:'유민', redTeamSup:'승준'},
        {rowNum:77, gameId:7800054783, blueTeamTop:'성재', blueTeamJug:'해용', blueTeamMid:'정호', blueTeamAdc:'재섭', blueTeamSup:'승준', redTeamTop:'대훈', redTeamJug:'광호', redTeamMid:'유민', redTeamAdc:'지훈', redTeamSup:'문석'},
        {rowNum:78, gameId:7800181301, blueTeamTop:'재섭', blueTeamJug:'승준', blueTeamMid:'해용', blueTeamAdc:'정호', blueTeamSup:'성재', redTeamTop:'대훈', redTeamJug:'지훈', redTeamMid:'문석', redTeamAdc:'광호', redTeamSup:'유민'},
        
    ]