
export const autoPlayerData:{
        rowNum:number,
        gameId:number,
        teamBlueTop:string,
        teamBlueJug:string,
        teamBlueMid:string,
        teamBlueAdc:string,
        teamBlueSup:string,
        teamRedTop:string,
        teamRedJug:string,
        teamRedMid:string,
        teamRedAdc:string,
        teamRedSup:string
    }[] = [
        {rowNum:1, gameId:7389173588, teamBlueTop:'인석', teamBlueJug:'승준', teamBlueMid:'경우', teamBlueAdc:'재섭', teamBlueSup:'대훈', teamRedTop:'문석', teamRedJug:'성재', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'현석'},
        {rowNum:2, gameId:7389279181, teamBlueTop:'성재', teamBlueJug:'지훈', teamBlueMid:'문석', teamBlueAdc:'광호', teamBlueSup:'현석', teamRedTop:'대훈', teamRedJug:'재섭', teamRedMid:'인석', teamRedAdc:'경우', teamRedSup:'승준'},
        {rowNum:3, gameId:7389336543, teamBlueTop:'광호', teamBlueJug:'대훈', teamBlueMid:'인석', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'문석', teamRedJug:'재섭', teamRedMid:'경우', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:4, gameId:7389485402, teamBlueTop:'재섭', teamBlueJug:'승준', teamBlueMid:'경우', teamBlueAdc:'문석', teamBlueSup:'현석', teamRedTop:'인석', teamRedJug:'대훈', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:5, gameId:7442713195, teamBlueTop:'문석', teamBlueJug:'인석', teamBlueMid:'성재', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'굴비', teamRedJug:'재섭', teamRedMid:'해용', teamRedAdc:'지훈', teamRedSup:'대훈'},
        {rowNum:6, gameId:7442792366, teamBlueTop:'지훈', teamBlueJug:'해용', teamBlueMid:'굴비', teamBlueAdc:'재섭', teamBlueSup:'대훈', teamRedTop:'인석', teamRedJug:'성재', teamRedMid:'문석', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:7, gameId:7442889331, teamBlueTop:'해용', teamBlueJug:'대훈', teamBlueMid:'재섭', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'굴비', teamRedJug:'인석', teamRedMid:'문석', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:8, gameId:7442990856, teamBlueTop:'문석', teamBlueJug:'굴비', teamBlueMid:'인석', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'대훈', teamRedJug:'해용', teamRedMid:'재섭', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:9, gameId:7443104399, teamBlueTop:'대훈', teamBlueJug:'재섭', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'굴비', teamRedJug:'승준', teamRedMid:'인석', teamRedAdc:'문석', teamRedSup:'성재'},
        {rowNum:10, gameId:7443216616, teamBlueTop:'대훈', teamBlueJug:'재섭', teamBlueMid:'문석', teamBlueAdc:'성재', teamBlueSup:'승준', teamRedTop:'인석', teamRedJug:'해용', teamRedMid:'지훈', teamRedAdc:'굴비', teamRedSup:'현석'},
        {rowNum:11, gameId:7450378540, teamBlueTop:'승준', teamBlueJug:'성재', teamBlueMid:'문석', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'해용', teamRedJug:'정호', teamRedMid:'인석', teamRedAdc:'재섭', teamRedSup:'대훈'},
        {rowNum:12, gameId:7450493494, teamBlueTop:'정호', teamBlueJug:'대훈', teamBlueMid:'인석', teamBlueAdc:'재섭', teamBlueSup:'해용', teamRedTop:'승준', teamRedJug:'문석', teamRedMid:'성재', teamRedAdc:'지훈', teamRedSup:'현석'},
        {rowNum:13, gameId:7450598630, teamBlueTop:'성재', teamBlueJug:'지훈', teamBlueMid:'승준', teamBlueAdc:'문석', teamBlueSup:'현석', teamRedTop:'정호', teamRedJug:'재섭', teamRedMid:'해용', teamRedAdc:'인석', teamRedSup:'대훈'},
        {rowNum:14, gameId:7450699576, teamBlueTop:'성재', teamBlueJug:'대훈', teamBlueMid:'인석', teamBlueAdc:'해용', teamBlueSup:'승준', teamRedTop:'정호', teamRedJug:'문석', teamRedMid:'지훈', teamRedAdc:'재섭', teamRedSup:'현석'},
        {rowNum:15, gameId:7450763320, teamBlueTop:'대훈', teamBlueJug:'승준', teamBlueMid:'재섭', teamBlueAdc:'정호', teamBlueSup:'문석', teamRedTop:'인석', teamRedJug:'해용', teamRedMid:'성재', teamRedAdc:'지훈', teamRedSup:'현석'},
        {rowNum:16, gameId:7502087331, teamBlueTop:'인석', teamBlueJug:'성재', teamBlueMid:'광호', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'해용', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'승준', teamRedSup:'대훈'},
        {rowNum:17, gameId:7502173309, teamBlueTop:'대훈', teamBlueJug:'승준', teamBlueMid:'재섭', teamBlueAdc:'해용', teamBlueSup:'문석', teamRedTop:'광호', teamRedJug:'지훈', teamRedMid:'성재', teamRedAdc:'인석', teamRedSup:'현석'},
        {rowNum:18, gameId:7502237027, teamBlueTop:'광호', teamBlueJug:'지훈', teamBlueMid:'인석', teamBlueAdc:'성재', teamBlueSup:'현석', teamRedTop:'대훈', teamRedJug:'문석', teamRedMid:'해용', teamRedAdc:'재섭', teamRedSup:'승준'},
        {rowNum:19, gameId:7502324018, teamBlueTop:'문석', teamBlueJug:'승준', teamBlueMid:'대훈', teamBlueAdc:'재섭', teamBlueSup:'해용', teamRedTop:'인석', teamRedJug:'성재', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'현석'},
        {rowNum:20, gameId:7502433024, teamBlueTop:'인석', teamBlueJug:'성재', teamBlueMid:'광호', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'문석', teamRedJug:'재섭', teamRedMid:'해용', teamRedAdc:'승준', teamRedSup:'대훈'},
        {rowNum:21, gameId:7502556457, teamBlueTop:'문석', teamBlueJug:'재섭', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'대훈', teamRedTop:'인석', teamRedJug:'성재', teamRedMid:'승준', teamRedAdc:'광호', teamRedSup:'현석'},
        {rowNum:22, gameId:7502659665, teamBlueTop:'문석', teamBlueJug:'재섭', teamBlueMid:'광호', teamBlueAdc:'승준', teamBlueSup:'대훈', teamRedTop:'성재', teamRedJug:'인석', teamRedMid:'해용', teamRedAdc:'지훈', teamRedSup:'현석'},
        {rowNum:23, gameId:7502769879, teamBlueTop:'대훈', teamBlueJug:'인석', teamBlueMid:'재섭', teamBlueAdc:'광호', teamBlueSup:'문석', teamRedTop:'성재', teamRedJug:'지훈', teamRedMid:'해용', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:24, gameId:7513016885, teamBlueTop:'인석', teamBlueJug:'지훈', teamBlueMid:'해용', teamBlueAdc:'내색', teamBlueSup:'대방', teamRedTop:'문석', teamRedJug:'재섭', teamRedMid:'광호', teamRedAdc:'승준', teamRedSup:'성재'},
        {rowNum:25, gameId:7513130503, teamBlueTop:'문석', teamBlueJug:'승준', teamBlueMid:'재섭', teamBlueAdc:'광호', teamBlueSup:'성재', teamRedTop:'지훈', teamRedJug:'해용', teamRedMid:'인석', teamRedAdc:'내색', teamRedSup:'대방'},
        {rowNum:26, gameId:7513262561, teamBlueTop:'인석', teamBlueJug:'지훈', teamBlueMid:'해용', teamBlueAdc:'내색', teamBlueSup:'대방', teamRedTop:'재섭', teamRedJug:'광호', teamRedMid:'문석', teamRedAdc:'성재', teamRedSup:'승준'},
        {rowNum:27, gameId:7513354415, teamBlueTop:'성재', teamBlueJug:'승준', teamBlueMid:'광호', teamBlueAdc:'문석', teamBlueSup:'재섭', teamRedTop:'지훈', teamRedJug:'해용', teamRedMid:'인석', teamRedAdc:'내색', teamRedSup:'대방'},
        {rowNum:28, gameId:7513445971, teamBlueTop:'지훈', teamBlueJug:'인석', teamBlueMid:'해용', teamBlueAdc:'내색', teamBlueSup:'대방', teamRedTop:'광호', teamRedJug:'성재', teamRedMid:'승준', teamRedAdc:'재섭', teamRedSup:'문석'},
        {rowNum:29, gameId:7513530035, teamBlueTop:'광호', teamBlueJug:'성재', teamBlueMid:'문석', teamBlueAdc:'재섭', teamBlueSup:'승준', teamRedTop:'해용', teamRedJug:'인석', teamRedMid:'지훈', teamRedAdc:'내색', teamRedSup:'대방'},
        {rowNum:30, gameId:7523345710, teamBlueTop:'성재', teamBlueJug:'재섭', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'문석', teamRedTop:'재희', teamRedJug:'승준', teamRedMid:'광호', teamRedAdc:'경우', teamRedSup:'인석'},
        {rowNum:31, gameId:7523437352, teamBlueTop:'승준', teamBlueJug:'경우', teamBlueMid:'인석', teamBlueAdc:'재희', teamBlueSup:'광호', teamRedTop:'문석', teamRedJug:'성재', teamRedMid:'지훈', teamRedAdc:'재섭', teamRedSup:'해용'},
        {rowNum:32, gameId:7523508506, teamBlueTop:'해용', teamBlueJug:'성재', teamBlueMid:'지훈', teamBlueAdc:'재섭', teamBlueSup:'문석', teamRedTop:'경우', teamRedJug:'재희', teamRedMid:'광호', teamRedAdc:'승준', teamRedSup:'인석'},
        {rowNum:33, gameId:7523613038, teamBlueTop:'재희', teamBlueJug:'인석', teamBlueMid:'광호', teamBlueAdc:'경우', teamBlueSup:'승준', teamRedTop:'성재', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'지훈', teamRedSup:'해용'},
        {rowNum:34, gameId:7523737287, teamBlueTop:'재희', teamBlueJug:'승준', teamBlueMid:'경우', teamBlueAdc:'광호', teamBlueSup:'인석', teamRedTop:'해용', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:35, gameId:7523820335, teamBlueTop:'문석', teamBlueJug:'해용', teamBlueMid:'재섭', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'경우', teamRedJug:'인석', teamRedMid:'재희', teamRedAdc:'광호', teamRedSup:'승준'},
        {rowNum:36, gameId:7564075776, teamBlueTop:'광호', teamBlueJug:'재섭', teamBlueMid:'성재', teamBlueAdc:'지훈', teamBlueSup:'인석', teamRedTop:'대훈', teamRedJug:'정호', teamRedMid:'해용', teamRedAdc:'경우', teamRedSup:'승준'},
        {rowNum:37, gameId:7564162106, teamBlueTop:'정호', teamBlueJug:'대훈', teamBlueMid:'승준', teamBlueAdc:'경우', teamBlueSup:'해용', teamRedTop:'재섭', teamRedJug:'인석', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:38, gameId:7564227398, teamBlueTop:'재섭', teamBlueJug:'성재', teamBlueMid:'인석', teamBlueAdc:'광호', teamBlueSup:'지훈', teamRedTop:'해용', teamRedJug:'경우', teamRedMid:'정호', teamRedAdc:'대훈', teamRedSup:'승준'},
        {rowNum:39, gameId:7564306026, teamBlueTop:'대훈', teamBlueJug:'경우', teamBlueMid:'정호', teamBlueAdc:'승준', teamBlueSup:'해용', teamRedTop:'인석', teamRedJug:'지훈', teamRedMid:'성재', teamRedAdc:'광호', teamRedSup:'재섭'},
        {rowNum:40, gameId:7564354139, teamBlueTop:'성재', teamBlueJug:'재섭', teamBlueMid:'광호', teamBlueAdc:'지훈', teamBlueSup:'인석', teamRedTop:'해용', teamRedJug:'정호', teamRedMid:'승준', teamRedAdc:'경우', teamRedSup:'대훈'},
        {rowNum:41, gameId:7573287104, teamBlueTop:'문석', teamBlueJug:'성재', teamBlueMid:'지훈', teamBlueAdc:'광호', teamBlueSup:'대훈', teamRedTop:'유민', teamRedJug:'승준', teamRedMid:'재섭', teamRedAdc:'경우', teamRedSup:'인석'},
        {rowNum:42, gameId:7573368098, teamBlueTop:'경우', teamBlueJug:'인석', teamBlueMid:'유민', teamBlueAdc:'승준', teamBlueSup:'문석', teamRedTop:'성재', teamRedJug:'광호', teamRedMid:'재섭', teamRedAdc:'지훈', teamRedSup:'대훈'},
        {rowNum:43, gameId:7573437650, teamBlueTop:'대훈', teamBlueJug:'재섭', teamBlueMid:'광호', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'인석', teamRedJug:'승준', teamRedMid:'경우', teamRedAdc:'문석', teamRedSup:'유민'},
        {rowNum:44, gameId:7573494032, teamBlueTop:'문석', teamBlueJug:'경우', teamBlueMid:'인석', teamBlueAdc:'유민', teamBlueSup:'승준', teamRedTop:'대훈', teamRedJug:'성재', teamRedMid:'재섭', teamRedAdc:'지훈', teamRedSup:'광호'},
        {rowNum:45, gameId:7573526592, teamBlueTop:'성재', teamBlueJug:'지훈', teamBlueMid:'경우', teamBlueAdc:'문석', teamBlueSup:'대훈', teamRedTop:'유민', teamRedJug:'재섭', teamRedMid:'광호', teamRedAdc:'승준', teamRedSup:'인석'},
        {rowNum:46, gameId:7573589418, teamBlueTop:'경우', teamBlueJug:'대훈', teamBlueMid:'광호', teamBlueAdc:'재섭', teamBlueSup:'승준', teamRedTop:'문석', teamRedJug:'인석', teamRedMid:'유민', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:47, gameId:7615805208, teamBlueTop:'해용', teamBlueJug:'승준', teamBlueMid:'정호', teamBlueAdc:'경우', teamBlueSup:'현석', teamRedTop:'태훈', teamRedJug:'인석', teamRedMid:'문석', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:48, gameId:7615880494, teamBlueTop:'태훈', teamBlueJug:'문석', teamBlueMid:'인석', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'정호', teamRedJug:'승준', teamRedMid:'경우', teamRedAdc:'해용', teamRedSup:'현석'},
        {rowNum:49, gameId:7615971149, teamBlueTop:'해용', teamBlueJug:'정호', teamBlueMid:'경우', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'성재', teamRedJug:'태훈', teamRedMid:'인석', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:50, gameId:7616037560, teamBlueTop:'태훈', teamBlueJug:'성재', teamBlueMid:'지훈', teamBlueAdc:'문석', teamBlueSup:'인석', teamRedTop:'현석', teamRedJug:'정호', teamRedMid:'승준', teamRedAdc:'경우', teamRedSup:'해용'},
        {rowNum:51, gameId:7616130103, teamBlueTop:'정호', teamBlueJug:'해용', teamBlueMid:'경우', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'인석', teamRedJug:'성재', teamRedMid:'태훈', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:52, gameId:7616180111, teamBlueTop:'인석', teamBlueJug:'태훈', teamBlueMid:'성재', teamBlueAdc:'지훈', teamBlueSup:'문석', teamRedTop:'정호', teamRedJug:'경우', teamRedMid:'해용', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:53, gameId:7616296480, teamBlueTop:'경우', teamBlueJug:'해용', teamBlueMid:'문석', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'정호', teamRedJug:'성재', teamRedMid:'인석', teamRedAdc:'지훈', teamRedSup:'유민'},
        {rowNum:54, gameId:7616373538, teamBlueTop:'정호', teamBlueJug:'인석', teamBlueMid:'유민', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'해용', teamRedJug:'승준', teamRedMid:'문석', teamRedAdc:'경우', teamRedSup:'현석'},
        {rowNum:55, gameId:7627535812, teamBlueTop:'정호', teamBlueJug:'인석', teamBlueMid:'지훈', teamBlueAdc:'경우', teamBlueSup:'대훈', teamRedTop:'문석', teamRedJug:'성재', teamRedMid:'재섭', teamRedAdc:'승준', teamRedSup:'해용'},
        {rowNum:56, gameId:7627620930, teamBlueTop:'성재', teamBlueJug:'해용', teamBlueMid:'재섭', teamBlueAdc:'승준', teamBlueSup:'문석', teamRedTop:'경우', teamRedJug:'대훈', teamRedMid:'정호', teamRedAdc:'지훈', teamRedSup:'인석'},
        {rowNum:57, gameId:7627716729, teamBlueTop:'인석', teamBlueJug:'지훈', teamBlueMid:'경우', teamBlueAdc:'정호', teamBlueSup:'대훈', teamRedTop:'승준', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'해용', teamRedSup:'성재'},
        {rowNum:58, gameId:7627831324, teamBlueTop:'해용', teamBlueJug:'재섭', teamBlueMid:'승준', teamBlueAdc:'문석', teamBlueSup:'성재', teamRedTop:'정호', teamRedJug:'인석', teamRedMid:'지훈', teamRedAdc:'경우', teamRedSup:'대훈'},
        {rowNum:59, gameId:7627909742, teamBlueTop:'지훈', teamBlueJug:'성재', teamBlueMid:'해용', teamBlueAdc:'문석', teamBlueSup:'승준', teamRedTop:'인석', teamRedJug:'재섭', teamRedMid:'경우', teamRedAdc:'정호', teamRedSup:'대훈'},
        {rowNum:60, gameId:7709795533, teamBlueTop:'규창', teamBlueJug:'성재', teamBlueMid:'해용', teamBlueAdc:'승준', teamBlueSup:'대훈', teamRedTop:'지훈', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'광호', teamRedSup:'정호'},
        {rowNum:61, gameId:7709838944, teamBlueTop:'성재', teamBlueJug:'승준', teamBlueMid:'광호', teamBlueAdc:'해용', teamBlueSup:'대훈', teamRedTop:'규창', teamRedJug:'재섭', teamRedMid:'정호', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:62, gameId:7709935603, teamBlueTop:'규창', teamBlueJug:'재섭', teamBlueMid:'정호', teamBlueAdc:'지훈', teamBlueSup:'문석', teamRedTop:'대훈', teamRedJug:'성재', teamRedMid:'해용', teamRedAdc:'광호', teamRedSup:'승준'},
        {rowNum:63, gameId:7709998273, teamBlueTop:'광호', teamBlueJug:'해용', teamBlueMid:'재섭', teamBlueAdc:'승준', teamBlueSup:'대훈', teamRedTop:'규창', teamRedJug:'성재', teamRedMid:'정호', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:64, gameId:7710067686, teamBlueTop:'규창', teamBlueJug:'지훈', teamBlueMid:'문석', teamBlueAdc:'정호', teamBlueSup:'성재', teamRedTop:'승준', teamRedJug:'해용', teamRedMid:'재섭', teamRedAdc:'광호', teamRedSup:'대훈'},
        {rowNum:65, gameId:7710150820, teamBlueTop:'규창', teamBlueJug:'성재', teamBlueMid:'지훈', teamBlueAdc:'정호', teamBlueSup:'문석', teamRedTop:'해용', teamRedJug:'대훈', teamRedMid:'재섭', teamRedAdc:'승준', teamRedSup:'광호'},
        {rowNum:66, gameId:7710221890, teamBlueTop:'규창', teamBlueJug:'문석', teamBlueMid:'정호', teamBlueAdc:'재섭', teamBlueSup:'승준', teamRedTop:'성재', teamRedJug:'해용', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'대훈'},
        {rowNum:67, gameId:7768749952, teamBlueTop:'성재', teamBlueJug:'인석', teamBlueMid:'해용', teamBlueAdc:'승준', teamBlueSup:'현석', teamRedTop:'대훈', teamRedJug:'재섭', teamRedMid:'굴비', teamRedAdc:'정호', teamRedSup:'지훈'},
        {rowNum:68, gameId:7768861557, teamBlueTop:'지훈', teamBlueJug:'정호', teamBlueMid:'굴비', teamBlueAdc:'재섭', teamBlueSup:'대훈', teamRedTop:'인석', teamRedJug:'승준', teamRedMid:'해용', teamRedAdc:'성재', teamRedSup:'현석'},
        {rowNum:69, gameId:7768951480, teamBlueTop:'굴비', teamBlueJug:'정호', teamBlueMid:'재섭', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'대훈', teamRedJug:'성재', teamRedMid:'해용', teamRedAdc:'인석', teamRedSup:'승준'},
        {rowNum:70, gameId:7769044477, teamBlueTop:'인석', teamBlueJug:'성재', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'재섭', teamRedJug:'대훈', teamRedMid:'굴비', teamRedAdc:'정호', teamRedSup:'승준'},
        {rowNum:71, gameId:7769150584, teamBlueTop:'성재', teamBlueJug:'정호', teamBlueMid:'지훈', teamBlueAdc:'재섭', teamBlueSup:'인석', teamRedTop:'대훈', teamRedJug:'굴비', teamRedMid:'해용', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:72, gameId:7799639480, teamBlueTop:'대훈', teamBlueJug:'정호', teamBlueMid:'해용', teamBlueAdc:'승준', teamBlueSup:'문석', teamRedTop:'성재', teamRedJug:'지훈', teamRedMid:'광호', teamRedAdc:'재섭', teamRedSup:'유민'},
        {rowNum:73, gameId:7799708953, teamBlueTop:'성재', teamBlueJug:'재섭', teamBlueMid:'광호', teamBlueAdc:'지훈', teamBlueSup:'유민', teamRedTop:'정호', teamRedJug:'해용', teamRedMid:'문석', teamRedAdc:'승준', teamRedSup:'대훈'},
        {rowNum:74, gameId:7799787516, teamBlueTop:'정호', teamBlueJug:'승준', teamBlueMid:'문석', teamBlueAdc:'해용', teamBlueSup:'대훈', teamRedTop:'유민', teamRedJug:'광호', teamRedMid:'지훈', teamRedAdc:'재섭', teamRedSup:'성재'},
        {rowNum:75, gameId:7799863622, teamBlueTop:'성재', teamBlueJug:'재섭', teamBlueMid:'지훈', teamBlueAdc:'광호', teamBlueSup:'유민', teamRedTop:'정호', teamRedJug:'대훈', teamRedMid:'해용', teamRedAdc:'문석', teamRedSup:'승준'},
        {rowNum:76, gameId:7799967095, teamBlueTop:'광호', teamBlueJug:'재섭', teamBlueMid:'지훈', teamBlueAdc:'정호', teamBlueSup:'성재', teamRedTop:'문석', teamRedJug:'대훈', teamRedMid:'해용', teamRedAdc:'유민', teamRedSup:'승준'},
        {rowNum:77, gameId:7800054783, teamBlueTop:'성재', teamBlueJug:'해용', teamBlueMid:'정호', teamBlueAdc:'재섭', teamBlueSup:'승준', teamRedTop:'대훈', teamRedJug:'광호', teamRedMid:'유민', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:78, gameId:7800181301, teamBlueTop:'재섭', teamBlueJug:'승준', teamBlueMid:'해용', teamBlueAdc:'정호', teamBlueSup:'성재', teamRedTop:'대훈', teamRedJug:'지훈', teamRedMid:'문석', teamRedAdc:'광호', teamRedSup:'유민'},
        {rowNum:79, gameId:7844109683, teamBlueTop:'해용', teamBlueJug:'재섭', teamBlueMid:'승준', teamBlueAdc:'인석', teamBlueSup:'성재', teamRedTop:'문석', teamRedJug:'대훈', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'유민'},
        {rowNum:80, gameId:7844226956, teamBlueTop:'재섭', teamBlueJug:'광호', teamBlueMid:'문석', teamBlueAdc:'성재', teamBlueSup:'대훈', teamRedTop:'유민', teamRedJug:'해용', teamRedMid:'승준', teamRedAdc:'지훈', teamRedSup:'인석'},
        {rowNum:81, gameId:7844339938, teamBlueTop:'문석', teamBlueJug:'광호', teamBlueMid:'지훈', teamBlueAdc:'재섭', teamBlueSup:'대훈', teamRedTop:'해용', teamRedJug:'승준', teamRedMid:'유민', teamRedAdc:'성재', teamRedSup:'인석'},
        {rowNum:82, gameId:7844488507, teamBlueTop:'성재', teamBlueJug:'인석', teamBlueMid:'유민', teamBlueAdc:'해용', teamBlueSup:'승준', teamRedTop:'대훈', teamRedJug:'재섭', teamRedMid:'지훈', teamRedAdc:'광호', teamRedSup:'문석'},
        {rowNum:83, gameId:7844570967, teamBlueTop:'승준', teamBlueJug:'성재', teamBlueMid:'인석', teamBlueAdc:'유민', teamBlueSup:'해용', teamRedTop:'지훈', teamRedJug:'재섭', teamRedMid:'광호', teamRedAdc:'문석', teamRedSup:'대훈'},
        {rowNum:84, gameId:7844707384, teamBlueTop:'문석', teamBlueJug:'승준', teamBlueMid:'유민', teamBlueAdc:'재섭', teamBlueSup:'성재', teamRedTop:'대훈', teamRedJug:'인석', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'해용'},
        {rowNum:85, gameId:7873258596, teamBlueTop:'인석', teamBlueJug:'문석', teamBlueMid:'재섭', teamBlueAdc:'지훈', teamBlueSup:'대훈', teamRedTop:'정호', teamRedJug:'성재', teamRedMid:'해용', teamRedAdc:'승준', teamRedSup:'현석'},
        {rowNum:86, gameId:7873353455, teamBlueTop:'정호', teamBlueJug:'승준', teamBlueMid:'대훈', teamBlueAdc:'지훈', teamBlueSup:'문석', teamRedTop:'인석', teamRedJug:'해용', teamRedMid:'재섭', teamRedAdc:'성재', teamRedSup:'현석'},
        {rowNum:87, gameId:7873471822, teamBlueTop:'재섭', teamBlueJug:'인석', teamBlueMid:'승준', teamBlueAdc:'해용', teamBlueSup:'대훈', teamRedTop:'성재', teamRedJug:'문석', teamRedMid:'지훈', teamRedAdc:'정호', teamRedSup:'현석'},
        {rowNum:88, gameId:7873576495, teamBlueTop:'해용', teamBlueJug:'대훈', teamBlueMid:'재섭', teamBlueAdc:'성재', teamBlueSup:'현석', teamRedTop:'문석', teamRedJug:'정호', teamRedMid:'인석', teamRedAdc:'지훈', teamRedSup:'승준'},
        {rowNum:89, gameId:7873693386, teamBlueTop:'재섭', teamBlueJug:'인석', teamBlueMid:'해용', teamBlueAdc:'문석', teamBlueSup:'현석', teamRedTop:'대훈', teamRedJug:'성재', teamRedMid:'지훈', teamRedAdc:'정호', teamRedSup:'승준'},
        {rowNum:90, gameId:7895822558, teamBlueTop:'진현', teamBlueJug:'굴비', teamBlueMid:'문석', teamBlueAdc:'재섭', teamBlueSup:'대훈', teamRedTop:'해용', teamRedJug:'인석', teamRedMid:'현석', teamRedAdc:'지훈', teamRedSup:'성재'},
        {rowNum:91, gameId:7895911825, teamBlueTop:'성재', teamBlueJug:'대훈', teamBlueMid:'재섭', teamBlueAdc:'문석', teamBlueSup:'현석', teamRedTop:'진현', teamRedJug:'굴비', teamRedMid:'인석', teamRedAdc:'지훈', teamRedSup:'해용'},
        {rowNum:92, gameId:7896018721, teamBlueTop:'문석', teamBlueJug:'지훈', teamBlueMid:'성재', teamBlueAdc:'굴비', teamBlueSup:'현석', teamRedTop:'진현', teamRedJug:'인석', teamRedMid:'해용', teamRedAdc:'재섭', teamRedSup:'대훈'},
        {rowNum:93, gameId:7918030346, teamBlueTop:'규창', teamBlueJug:'성재', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'대훈', teamRedTop:'재섭', teamRedJug:'정호', teamRedMid:'광호', teamRedAdc:'문석', teamRedSup:'승준'},
        {rowNum:94, gameId:7918096061, teamBlueTop:'규창', teamBlueJug:'대훈', teamBlueMid:'문석', teamBlueAdc:'지훈', teamBlueSup:'해용', teamRedTop:'재섭', teamRedJug:'승준', teamRedMid:'성재', teamRedAdc:'정호', teamRedSup:'광호'},
        {rowNum:95, gameId:7918195794, teamBlueTop:'정호', teamBlueJug:'재섭', teamBlueMid:'해용', teamBlueAdc:'문석', teamBlueSup:'성재', teamRedTop:'규창', teamRedJug:'승준', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'대훈'},
        {rowNum:96, gameId:7918295255, teamBlueTop:'대훈', teamBlueJug:'광호', teamBlueMid:'정호', teamBlueAdc:'지훈', teamBlueSup:'성재', teamRedTop:'규창', teamRedJug:'해용', teamRedMid:'재섭', teamRedAdc:'문석', teamRedSup:'승준'},
        {rowNum:97, gameId:7918391029, teamBlueTop:'규창', teamBlueJug:'정호', teamBlueMid:'문석', teamBlueAdc:'승준', teamBlueSup:'성재', teamRedTop:'대훈', teamRedJug:'재섭', teamRedMid:'지훈', teamRedAdc:'광호', teamRedSup:'해용'},
        {rowNum:98, gameId:7918451671, teamBlueTop:'규창', teamBlueJug:'승준', teamBlueMid:'재섭', teamBlueAdc:'정호', teamBlueSup:'성재', teamRedTop:'해용', teamRedJug:'대훈', teamRedMid:'광호', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:99, gameId:7944676720, teamBlueTop:'성재', teamBlueJug:'재섭', teamBlueMid:'문석', teamBlueAdc:'지훈', teamBlueSup:'해용', teamRedTop:'정호', teamRedJug:'대훈', teamRedMid:'광호', teamRedAdc:'승준', teamRedSup:'견희'},
        {rowNum:100, gameId:7944781664, teamBlueTop:'대훈', teamBlueJug:'정호', teamBlueMid:'승준', teamBlueAdc:'광호', teamBlueSup:'견희', teamRedTop:'성재', teamRedJug:'해용', teamRedMid:'재섭', teamRedAdc:'지훈', teamRedSup:'문석'},
        {rowNum:101, gameId:7944892077, teamBlueTop:'문석', teamBlueJug:'승준', teamBlueMid:'해용', teamBlueAdc:'지훈', teamBlueSup:'견희', teamRedTop:'대훈', teamRedJug:'정호', teamRedMid:'광호', teamRedAdc:'재섭', teamRedSup:'성재'},
        {rowNum:102, gameId:7945040206, teamBlueTop:'정호', teamBlueJug:'재섭', teamBlueMid:'문석', teamBlueAdc:'승준', teamBlueSup:'해용', teamRedTop:'성재', teamRedJug:'지훈', teamRedMid:'견희', teamRedAdc:'광호', teamRedSup:'대훈'},
        {rowNum:103, gameId:7979573346, teamBlueTop:'성재', teamBlueJug:'해용', teamBlueMid:'인석', teamBlueAdc:'승준', teamBlueSup:'정호', teamRedTop:'대훈', teamRedJug:'재섭', teamRedMid:'문석', teamRedAdc:'지훈', teamRedSup:'유민'},
        {rowNum:104, gameId:7979716105, teamBlueTop:'해용', teamBlueJug:'대훈', teamBlueMid:'지훈', teamBlueAdc:'재섭', teamBlueSup:'성재', teamRedTop:'문석', teamRedJug:'승준', teamRedMid:'유민', teamRedAdc:'정호', teamRedSup:'인석'},
        {rowNum:105, gameId:7979845479, teamBlueTop:'인석', teamBlueJug:'정호', teamBlueMid:'문석', teamBlueAdc:'유민', teamBlueSup:'승준', teamRedTop:'성재', teamRedJug:'재섭', teamRedMid:'대훈', teamRedAdc:'지훈', teamRedSup:'해용'},
        {rowNum:106, gameId:7979965281, teamBlueTop:'지훈', teamBlueJug:'정호', teamBlueMid:'유민', teamBlueAdc:'재섭', teamBlueSup:'문석', teamRedTop:'승준', teamRedJug:'성재', teamRedMid:'해용', teamRedAdc:'인석', teamRedSup:'대훈'},
        {rowNum:107, gameId:7980136174, teamBlueTop:'성재', teamBlueJug:'승준', teamBlueMid:'유민', teamBlueAdc:'문석', teamBlueSup:'대훈', teamRedTop:'정호', teamRedJug:'인석', teamRedMid:'해용', teamRedAdc:'지훈', teamRedSup:'재섭'},
        {rowNum:108, gameId:8001716280, teamBlueTop:'성재', teamBlueJug:'광호', teamBlueMid:'문석', teamBlueAdc:'지훈', teamBlueSup:'현석', teamRedTop:'인석', teamRedJug:'대훈', teamRedMid:'재섭', teamRedAdc:'유민', teamRedSup:'해용'},
        {rowNum:109, gameId:8001816763, teamBlueTop:'성재', teamBlueJug:'지훈', teamBlueMid:'문석', teamBlueAdc:'유민', teamBlueSup:'현석', teamRedTop:'광호', teamRedJug:'대훈', teamRedMid:'해용', teamRedAdc:'재섭', teamRedSup:'인석'},
        {rowNum:110, gameId:8001944528, teamBlueTop:'대훈', teamBlueJug:'성재', teamBlueMid:'유민', teamBlueAdc:'문석', teamBlueSup:'현석', teamRedTop:'해용', teamRedJug:'지훈', teamRedMid:'재섭', teamRedAdc:'광호', teamRedSup:'인석'},
        {rowNum:111, gameId:8002099519, teamBlueTop:'재섭', teamBlueJug:'해용', teamBlueMid:'인석', teamBlueAdc:'성재', teamBlueSup:'현석', teamRedTop:'문석', teamRedJug:'광호', teamRedMid:'유민', teamRedAdc:'지훈', teamRedSup:'대훈'},
        {rowNum:112, gameId:8002205128, teamBlueTop:'성재', teamBlueJug:'인석', teamBlueMid:'지훈', teamBlueAdc:'유민', teamBlueSup:'재섭', teamRedTop:'문석', teamRedJug:'대훈', teamRedMid:'해용', teamRedAdc:'광호', teamRedSup:'현석'},
    ]